
import static com.sun.webkit.perf.WCFontPerfLogger.reset;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

//chart import 
import org.jfree.chart.JFreeChart; 
import org.jfree.chart.ChartFactory; 
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.ChartUtilities; 
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author oshad
 */
public class Couplingweight extends javax.swing.JFrame {

    
    FileReader fr;
    String code;
    private int LineNo = 1;
    File ff;
    private int sumControl = 0;
    public Couplingweight() {
        initComponents();
        jTableDesign();
    }

      public Couplingweight(File ff) throws IOException {
        initComponents();
        this.ff = ff;

        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        jTableDesign();
       

        //setTableData(ff);
        //lineArray();
        //condition(ff);
        
        //Ccs(ff);
    }
     private void jTableDesign() {
        CTable.setRowHeight(40);
        CTable.setShowGrid(true);
        CTable.setGridColor(new Color(153, 153, 255));
        CTable.setSelectionBackground(Color.DARK_GRAY);

        JTableHeader tableHeader = CTable.getTableHeader();
        tableHeader.setBackground(new Color(153, 153, 255));
        tableHeader.setForeground(Color.BLACK);
        tableHeader.setPreferredSize(new Dimension(70, 70));
        tableHeader.setFont(new Font("Arial", Font.BOLD, 12));
    }
     
     public int getSumControl() {
        return sumControl;
    } 
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Wmcms = new javax.swing.JTextField();
        Wr = new javax.swing.JTextField();
        Wrmrgvd = new javax.swing.JTextField();
        Wmcmd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea1 = new javax.swing.JTextArea();
        fileUpload = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        CTable = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        Wmcrms = new javax.swing.JTextField();
        Wmcrmd = new javax.swing.JTextField();
        Wrmcrms = new javax.swing.JTextField();
        Wrmcrmd = new javax.swing.JTextField();
        Wrmcms = new javax.swing.JTextField();
        Wrmcmd = new javax.swing.JTextField();
        Wmrgvs = new javax.swing.JTextField();
        Wmrgvd = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        WD1 = new javax.swing.JTextField();
        ifElse1 = new javax.swing.JTextField();
        CaseVariable9 = new javax.swing.JTextField();
        Swvariable1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextArea2 = new javax.swing.JTextArea();
        fileUpload1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        CTable1 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        CaseVariable10 = new javax.swing.JTextField();
        CaseVariable11 = new javax.swing.JTextField();
        CaseVariable12 = new javax.swing.JTextField();
        CaseVariable13 = new javax.swing.JTextField();
        CaseVariable14 = new javax.swing.JTextField();
        CaseVariable15 = new javax.swing.JTextField();
        CaseVariable16 = new javax.swing.JTextField();
        CaseVariable17 = new javax.swing.JTextField();
        Wrmrgvs = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Perpetua", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Weights related to the Coupling Factor");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(240, 20, 730, 42);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(600, 660, 150, 30);

        Wmcms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WmcmsActionPerformed(evt);
            }
        });
        jPanel1.add(Wmcms);
        Wmcms.setBounds(530, 330, 40, 25);

        Wr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WrActionPerformed(evt);
            }
        });
        jPanel1.add(Wr);
        Wr.setBounds(530, 300, 40, 25);

        Wrmrgvd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WrmrgvdActionPerformed(evt);
            }
        });
        jPanel1.add(Wrmrgvd);
        Wrmrgvd.setBounds(530, 660, 40, 25);

        Wmcmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WmcmdActionPerformed(evt);
            }
        });
        jPanel1.add(Wmcmd);
        Wmcmd.setBounds(530, 360, 40, 25);

        jLabel7.setBackground(new java.awt.Color(0, 204, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Coupling Type------------------------------");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 270, 490, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("------Weight ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(470, 270, 130, 20);

        TextArea1.setColumns(20);
        TextArea1.setRows(5);
        jScrollPane1.setViewportView(TextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 100, 550, 160);
        jPanel1.add(fileUpload);
        fileUpload.setBounds(40, 70, 400, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Upload");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(440, 70, 150, 30);

        CTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Line no", "Program statements", "Wr", "Wmcms", "Wmcmd", "Wmcrms", "Wmcrmd", "Wrmcrms", "Wrmcrmd", "Wrmcms", "Wrmcmd", "Wmrgvs", "Wmrgvd", "Wrmrgvs", "Wrmrgvd", "Ccp"
            }
        ));
        jScrollPane2.setViewportView(CTable);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(600, 70, 560, 570);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backSmall.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(40, 20, 60, 40);
        jPanel1.add(Wmcrms);
        Wmcrms.setBounds(530, 390, 40, 25);

        Wmcrmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WmcrmdActionPerformed(evt);
            }
        });
        jPanel1.add(Wmcrmd);
        Wmcrmd.setBounds(530, 420, 40, 25);
        jPanel1.add(Wrmcrms);
        Wrmcrms.setBounds(530, 450, 40, 25);
        jPanel1.add(Wrmcrmd);
        Wrmcrmd.setBounds(530, 480, 40, 25);
        jPanel1.add(Wrmcms);
        Wrmcms.setBounds(530, 510, 40, 25);

        Wrmcmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WrmcmdActionPerformed(evt);
            }
        });
        jPanel1.add(Wrmcmd);
        Wrmcmd.setBounds(530, 540, 40, 25);
        jPanel1.add(Wmrgvs);
        Wmrgvs.setBounds(530, 570, 40, 25);
        jPanel1.add(Wmrgvd);
        Wmrgvd.setBounds(530, 600, 40, 25);

        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Perpetua", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Weights related to the control structure factor");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(240, 20, 730, 42);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Save");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(500, 660, 100, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("A conditional control structure such as an ‘if’ or ‘else-if’ condition");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(30, 300, 460, 17);
        jPanel2.add(WD1);
        WD1.setBounds(530, 330, 40, 20);

        ifElse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ifElse1ActionPerformed(evt);
            }
        });
        jPanel2.add(ifElse1);
        ifElse1.setBounds(530, 300, 40, 20);
        jPanel2.add(CaseVariable9);
        CaseVariable9.setBounds(530, 630, 40, 20);
        jPanel2.add(Swvariable1);
        Swvariable1.setBounds(530, 360, 40, 20);

        jLabel9.setBackground(new java.awt.Color(0, 204, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Control Structure Type------------------------------");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(30, 270, 490, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("------Weight ");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(470, 270, 130, 20);

        TextArea2.setColumns(20);
        TextArea2.setRows(5);
        jScrollPane3.setViewportView(TextArea2);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(40, 100, 550, 160);
        jPanel2.add(fileUpload1);
        fileUpload1.setBounds(40, 70, 400, 30);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Upload");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(440, 70, 150, 30);

        CTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Line no", "Program statements", "Wtcs", "NC", "Ccspps ", "Ccs "
            }
        ));
        jScrollPane4.setViewportView(CTable1);

        jPanel2.add(jScrollPane4);
        jScrollPane4.setBounds(600, 80, 580, 530);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backSmall.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(40, 20, 60, 40);
        jPanel2.add(CaseVariable10);
        CaseVariable10.setBounds(530, 390, 40, 20);
        jPanel2.add(CaseVariable11);
        CaseVariable11.setBounds(530, 420, 40, 20);
        jPanel2.add(CaseVariable12);
        CaseVariable12.setBounds(530, 450, 40, 20);
        jPanel2.add(CaseVariable13);
        CaseVariable13.setBounds(530, 480, 40, 20);
        jPanel2.add(CaseVariable14);
        CaseVariable14.setBounds(530, 510, 40, 20);
        jPanel2.add(CaseVariable15);
        CaseVariable15.setBounds(530, 540, 40, 20);
        jPanel2.add(CaseVariable16);
        CaseVariable16.setBounds(530, 570, 40, 20);
        jPanel2.add(CaseVariable17);
        CaseVariable17.setBounds(530, 600, 40, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 0, 0);
        jPanel1.add(Wrmrgvs);
        Wrmrgvs.setBounds(530, 630, 40, 25);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("Create Bar Chart");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(750, 660, 150, 30);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("Add All weight related dependencies before clicking");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(600, 690, 320, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("A recursive call");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("A regular method calling another regular method in the same file");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("A regular method calling another regular method in a different file ");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("A regular method calling a recursive method in the same file");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("A regular method calling a recursive method in a different file");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("A recursive method calling another recursive method in the same file ");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("A recursive method calling another recursive method in a different file ");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("A recursive method calling a regular method in the same file");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("A recursive method calling a regular method in a different file");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("A regular method referencing a global variable in the same file ");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("A regular method referencing a global variable in a different file ");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("A recursive method referencing a global variable in the same file");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("A recursive method referencing a global variable in a different file");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addGap(12, 12, 12)
                .addComponent(jLabel12)
                .addGap(13, 13, 13)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(13, 13, 13)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addGap(12, 12, 12)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addGap(11, 11, 11)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(40, 300, 480, 390);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setText("Reset");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(900, 660, 150, 30);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/world.jpg"))); // NOI18N
        jPanel1.add(jLabel23);
        jLabel23.setBounds(-10, 0, 1310, 800);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1355, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        DefaultTableModel model = (DefaultTableModel) CTable.getModel();
        int Wtcs = 0;
        int Nc =0;
        int Ccspps=0;
        int Ccs=0;
        //Coupling variables
        int Wr1 = 0;
        int Wmcms1 = 0;
        int Wmcmd1 = 0;
        int Wmcrms1 = 0;
        int Wmcrmd1 = 0;
        int Wrmcrms1 = 0;
        int Wrmcrmd1 = 0;
        int Wrmcms1 = 0;
        int Wrmcmd1 = 0;
        int Wmrgvs1 = 0;
        int Wmrgvd1 = 0;
        int Wrmrgvs1 = 0;
        int Wrmrgvd1 = 0;
        int Ccp = 0;
        int Tcp = 0;
        FileReader fr = null;
        try {
            fr = new FileReader(ff);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(weight.class.getName()).log(Level.SEVERE, null, ex);
        }
        BufferedReader br = new BufferedReader(fr);
              
        String strCurrentLine=null;
        try {
            strCurrentLine = br.readLine();
        } catch (IOException ex) {
            Logger.getLogger(weight.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        try {
            while ((strCurrentLine = br.readLine()) != null) {
                
                for(int i=0;i<strCurrentLine.length();i++)
                {
                    
                    if(strCurrentLine.trim().matches(".*(set|return|get).*"))
                    {
                        //Wtcs=Integer.parseInt(Wmcms.getText());
                        Wr1= Integer.parseInt(Wr.getText());
                     
                    }
        
                    else{
                        //Wtcs=0;
                        Wr1 = 0;
                    }
                    
                     if(strCurrentLine.trim().matches(".*(set|return|get).*")){
                         Wmcms1= Integer.parseInt(Wmcms.getText());
                         
                }
                else{
                    Wmcms1= 0;
                }
                
                  if(strCurrentLine.trim().matches(".*\\b((void|int|double|String)(\\s+|\\().*\\{).*")){
                    Wmcrms1= Integer.parseInt(Wmcrms.getText());
                    
                }
                else{
                    Wmcrms1= 0;
                }
                  
                if(strCurrentLine.trim().matches(".*\\b((void|int|double|String)(\\s+|\\().*\\{).*")){
                    Wrmcrms1= Integer.parseInt(Wrmcrms.getText());
                    
                }
                else{
                    Wrmcrms1= 0;
                }  
                
                    if(strCurrentLine.trim().matches(".*\\b((void|int|double|String)(\\s+|\\().*\\{).*")){
                    Wrmcms1= Integer.parseInt(Wrmcms.getText());
                
                }
                else{
                    Wrmcms1= 0;
                } 
                     if(strCurrentLine.trim().matches(".*private|public(.*?).*.*")){
                    Wmrgvs1= Integer.parseInt(Wmrgvs.getText());
           
                }
                else{
                    Wmrgvs1= 0;
                } 
                     
                  if(strCurrentLine.trim().matches(".*private|public int \\s*(\\S+).*")){
                    Wrmrgvs1= Integer.parseInt(Wrmrgvs.getText());
                 
                }
                else{
                    Wrmrgvs1= 0;
                }
                    
                    
                    
                    
                    
                    
                }
                
                if (strCurrentLine.trim().length() != 0) {
                    System.out.println(strCurrentLine);
                    strCurrentLine = strCurrentLine.trim();

                }
                if (strCurrentLine.contains("//")) {
                    System.out.println(strCurrentLine.substring(0, strCurrentLine.indexOf("//")));
                    strCurrentLine = strCurrentLine.substring(0, strCurrentLine.indexOf("//"));
                    
                }
                
                int total = 0;
                
                
                
                
                Object[] row = {LineNo++, strCurrentLine,Wr1,Wmcms1,Wmcmd1,Wmcrms1,Wmcrmd1,Wrmcrms1,Wrmcrmd1,Wrmcms1,Wrmcmd1,Wmrgvs1,Wmrgvd1,Wrmrgvs1,Wrmrgvd1,Ccp};
                model.addRow(row);
            }
        } catch (IOException ex) {
            Logger.getLogger(weight.class.getName()).log(Level.SEVERE, null, ex);
        }
        
     }
     public void  setWeightData(File ff) throws IOException {
         
        weight ne =new  weight();
        DefaultTableModel model = (DefaultTableModel) CTable.getModel();
        int Wtcs = 0;
        int Nc =0;
        int Ccspps=0;
        int Ccs=0;
        FileReader fr = new FileReader(ff);
        BufferedReader br = new BufferedReader(fr);
              
        String strCurrentLine=null;
        strCurrentLine = br.readLine();
       
        while ((strCurrentLine = br.readLine()) != null) {
          
            for(int i=0;i<strCurrentLine.length();i++)
            {
               
            if(strCurrentLine.trim().startsWith("for")||strCurrentLine.trim().startsWith("while")||strCurrentLine.trim().startsWith("do-while"))
            {
                //Wtcs=Integer.parseInt(FWD.getText());                
            }
            else if(strCurrentLine.trim().startsWith("if")||strCurrentLine.trim().startsWith("else if")||strCurrentLine.trim().startsWith("switch"))
            {
                ///Wtcs=Integer.parseInt(EIF.getText()); 
            }            
            else if(strCurrentLine.trim().startsWith("case"))
            {
               // Wtcs=Integer.parseInt(CaseV.getText()); 
            }
            else{
                
                Wtcs=0;
                                
                }
            
            }                                                                 
            Object[] row = {LineNo++, strCurrentLine, Wtcs, null, Ccspps,Ccs };            
            model.addRow(row);      
        }
        
        /*
        String one=ifElse.getText();
        String two=WD.getText();
        String three=Swvariable.getText();
        String four=CaseVariable.getText();
        //setVisible(false);
        //new interface02().setVisible(true);
        
        */
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          JFileChooser jf = new JFileChooser();
        int aa = jf.showOpenDialog(null);

        if(aa == JFileChooser.APPROVE_OPTION){
            char cbuf[] = null;
            ff = jf.getSelectedFile();
            fileUpload.setText(ff.getName());

            try {
                fr = new FileReader(ff);
                TextArea1.read(fr, "");
                code = TextArea1.getText();
            } catch (Exception ex) {
                Logger.getLogger(interface01.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                try {
                    fr.close();
                } catch (IOException ex) {
                    Logger.getLogger(interface01.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       setVisible(false);
       new interface01().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void WrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WrActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void ifElse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ifElse1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ifElse1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void WrmcmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WrmcmdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WrmcmdActionPerformed

    private void WmcrmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WmcrmdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WmcrmdActionPerformed

    private void WrmrgvdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WrmrgvdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WrmrgvdActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int Wr1 = 0;
        int Wmcms1 = 0;
        int Wmcmd1 = 0;
        int Wmcrms1 = 0;
        int Wmcrmd1 = 0;
        int Wrmcrms1 = 0;
        int Wrmcrmd1 = 0;
        int Wrmcms1 = 0;
        int Wrmcmd1 = 0;
        int Wmrgvs1 = 0;
        int Wmrgvd1 = 0;
        int Wrmrgvs1 = 0;
        int Wrmrgvd1 = 0;
         Wr1=Integer.parseInt(Wr.getText());
         Wmcms1=Integer.parseInt(Wmcms.getText());
         Wmcmd1=Integer.parseInt( Wmcmd.getText());
         Wmcrms1 =  Integer.parseInt(Wmcrms.getText());     
         Wmcrmd1 =Integer.parseInt( Wmcrmd.getText());
         Wrmcrms1 =Integer.parseInt( Wrmcrms.getText());
         Wrmcrmd1 =Integer.parseInt(Wrmcrmd.getText());
         Wrmcms1  = Integer.parseInt(Wrmcms.getText()); 
         Wrmcmd1 =  Integer.parseInt(Wrmcmd.getText());
         Wmrgvs1 =Integer.parseInt(Wmrgvs.getText());
         Wmrgvd1 =Integer.parseInt(Wmrgvd.getText());
         Wmrgvd1 =Integer.parseInt(Wmrgvd.getText());
         Wrmrgvs1 =Integer.parseInt(Wrmrgvs.getText());
         Wrmrgvd1 =   Integer.parseInt(Wrmrgvd.getText());     
          DefaultCategoryDataset dataset = new DefaultCategoryDataset( );
        
          //dataset.setValue(new int(Wr1),"values","weight");
            dataset.setValue(Wr1, "weight", "Wr");
            dataset.setValue(Wmcms1, "weight", "Wmcms");
            dataset.setValue(Wmcmd1, "weight", "Wmcmd");
            dataset.setValue(Wmcrms1, "weight", "Wmcrms");
            dataset.setValue(Wmcrmd1, "weight", "Wmcrmd");
            dataset.setValue(Wrmcrms1, "weight", "Wrmcrms");
            dataset.setValue(Wrmcrmd1, "weight", "Wrmcrmd");
            dataset.setValue(Wrmcms1, "weight", "Wrmcms");
            dataset.setValue(Wrmcmd1, "weight", "Wrmcmd");
            dataset.setValue(Wmrgvs1, "weight", "Wmrgvs");
            dataset.setValue(Wmrgvd1, "weight", "Wmrgvd");
            dataset.setValue(Wrmrgvs1, "weight", "Wrmrgvs");
            dataset.setValue(Wrmrgvd1, "weight", "Wrmrgvd");
            
            JFreeChart chart = ChartFactory.createBarChart3D("Coupling", "Factors", "weightage", dataset, PlotOrientation.VERTICAL, false, true, false);
            CategoryPlot p = chart.getCategoryPlot();
            ChartFrame frame = new ChartFrame("Bar Chart for coupling", chart);
            frame.setVisible(true);
            frame.setSize(600,550);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void WmcmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WmcmsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WmcmsActionPerformed

    private void WmcmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WmcmdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WmcmdActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       
        fileUpload.setText("");
        TextArea1.setText("");
        Wr.setText("");
        Wmcms.setText("");
        Wmcmd.setText(""); 
        Wmcrms.setText("");
        Wmcrmd.setText("");
        Wrmcrms.setText("");
        Wrmcrmd.setText("");
        Wrmcms.setText("");
        Wrmcmd.setText("");
        Wmcms.setText("");
        Wmrgvs.setText("");
        Wmrgvd.setText("");
        Wrmrgvs.setText("");
        Wrmrgvd.setText("");
        CTable.setModel(new DefaultTableModel(null, new String[]{"Line no", "Program statements", "Wr", "Wmcms", "Wmcmd", "Wmcrms", "Wmcrmd", "Wrmcrms","Wrmcrmd","Wrmcms","Wrmcmd","Wmrgvs","Wmrgvd","Wrmrgvs","Wrmrgvd","Ccp"}));
        
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(weight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(weight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(weight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(weight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new weight().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CTable;
    private javax.swing.JTable CTable1;
    private javax.swing.JTextField CaseVariable10;
    private javax.swing.JTextField CaseVariable11;
    private javax.swing.JTextField CaseVariable12;
    private javax.swing.JTextField CaseVariable13;
    private javax.swing.JTextField CaseVariable14;
    private javax.swing.JTextField CaseVariable15;
    private javax.swing.JTextField CaseVariable16;
    private javax.swing.JTextField CaseVariable17;
    private javax.swing.JTextField CaseVariable9;
    private javax.swing.JTextField Swvariable1;
    private javax.swing.JTextArea TextArea1;
    private javax.swing.JTextArea TextArea2;
    private javax.swing.JTextField WD1;
    private javax.swing.JTextField Wmcmd;
    private javax.swing.JTextField Wmcms;
    private javax.swing.JTextField Wmcrmd;
    private javax.swing.JTextField Wmcrms;
    private javax.swing.JTextField Wmrgvd;
    private javax.swing.JTextField Wmrgvs;
    private javax.swing.JTextField Wr;
    private javax.swing.JTextField Wrmcmd;
    private javax.swing.JTextField Wrmcms;
    private javax.swing.JTextField Wrmcrmd;
    private javax.swing.JTextField Wrmcrms;
    private javax.swing.JTextField Wrmrgvd;
    private javax.swing.JTextField Wrmrgvs;
    private javax.swing.JTextField fileUpload;
    private javax.swing.JTextField fileUpload1;
    private javax.swing.JTextField ifElse1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
