import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Weight3 extends javax.swing.JFrame {

    FileReader fr;
    String code;
    private int LineNo = 1;
    File ff;
    
    public Weight3() {
        initComponents();
        jTableDesign();
    }

      public Weight3(File ff) throws IOException {
        initComponents();
        this.ff = ff;

        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        jTableDesign();
       

        //setTableData(ff);
        //lineArray();
        //condition(ff);
        
        //Ccs(ff);
    }
     private void jTableDesign() {
        Mtable.setRowHeight(40);
        Mtable.setShowGrid(true);
        Mtable.setGridColor(new Color(153, 153, 255));
        Mtable.setSelectionBackground(Color.DARK_GRAY);

        JTableHeader tableHeader = Mtable.getTableHeader();
        tableHeader.setBackground(new Color(153, 153, 255));
        tableHeader.setForeground(Color.BLACK);
        tableHeader.setPreferredSize(new Dimension(70, 70));
        tableHeader.setFont(new Font("Arial", Font.BOLD, 12));
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        methodcomposite = new javax.swing.JTextField();
        methodprimitive = new javax.swing.JTextField();
        compositeparameter = new javax.swing.JTextField();
        methodreturn = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea1 = new javax.swing.JTextArea();
        fileUpload = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Mtable = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        primitiveparameter = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Perpetua", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Weights related to the method factor");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(310, 40, 730, 42);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(440, 630, 150, 30);

        methodcomposite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                methodcompositeActionPerformed(evt);
            }
        });
        jPanel1.add(methodcomposite);
        methodcomposite.setBounds(530, 500, 60, 30);

        methodprimitive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                methodprimitiveActionPerformed(evt);
            }
        });
        jPanel1.add(methodprimitive);
        methodprimitive.setBounds(530, 470, 60, 30);

        compositeparameter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compositeparameterActionPerformed(evt);
            }
        });
        jPanel1.add(compositeparameter);
        compositeparameter.setBounds(530, 590, 60, 30);

        methodreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                methodreturnActionPerformed(evt);
            }
        });
        jPanel1.add(methodreturn);
        methodreturn.setBounds(530, 530, 60, 30);

        jLabel7.setBackground(new java.awt.Color(0, 204, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Program Component------------------------------");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 440, 490, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("-------Weight ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(470, 440, 130, 20);

        TextArea1.setColumns(20);
        TextArea1.setRows(5);
        jScrollPane1.setViewportView(TextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 160, 550, 260);

        fileUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileUploadActionPerformed(evt);
            }
        });
        jPanel1.add(fileUpload);
        fileUpload.setBounds(40, 130, 400, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Upload");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(440, 130, 150, 30);

        Mtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Line no", "Program Statements", "Wmrt", "Npdtp", "Ncdtp", "Cm"
            }
        ));
        jScrollPane2.setViewportView(Mtable);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(600, 130, 580, 530);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backSmall.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(40, 20, 60, 40);

        primitiveparameter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primitiveparameterActionPerformed(evt);
            }
        });
        jPanel1.add(primitiveparameter);
        primitiveparameter.setBounds(530, 560, 60, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Method with a primitive return type");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Method with a composite return type");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Method with a void return type");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Primitive data type parameter");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Composite data type parameter");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(15, 15, 15)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(40, 470, 480, 150);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Create Bar Chart");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(290, 630, 150, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Add All weight related dependencies before clicking");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 670, 310, 17);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Reset");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(140, 630, 150, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/world.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1410, 800);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1372, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) Mtable.getModel();
        int Wmrt = 0;
        int Npdtp = 0;
        int Ncdtp = 0;
        int Wpdtp = 0;
        int Wcdtp =0;
        int Cm = 0;
        int count = 0;
        
        FileReader fr = null;
        try {
            fr = new FileReader(ff);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Weight3.class.getName()).log(Level.SEVERE, null, ex);
        }
        BufferedReader br = new BufferedReader(fr);
        
        String strCurrentLine = null;
        try {
            strCurrentLine = br.readLine();
        } catch (IOException ex) {
            Logger.getLogger(Weight3.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            while ((strCurrentLine = br.readLine()) != null) {
                
                for(int i=0;i<strCurrentLine.length();i++)
                {
                    
                    if(strCurrentLine.trim().startsWith("for")||strCurrentLine.trim().startsWith("while")||strCurrentLine.trim().startsWith("do-while"))
                    {
                        //Wtcs=Integer.parseInt(WD.getText());
                    }
                    else if(strCurrentLine.trim().startsWith("if")||strCurrentLine.trim().startsWith("else if"))
                    {
                        //Wtcs=Integer.parseInt(ifElse.getText());
                    }
                    else if(strCurrentLine.trim().startsWith("switch"))
                    {
                        //Wtcs=Integer.parseInt(Swvariable.getText());//CaseVariable
                    }
                    else if(strCurrentLine.trim().startsWith("case"))
                    {
                        //Wtcs=Integer.parseInt(CaseVariable.getText());
                    }
                    else{
                        
                        Cm=0;
                        
                    }
                    
                }
                
                int total = 0;
                
                total = total + ((strCurrentLine.length() - strCurrentLine.replaceAll("(?<!\\w)if(?!\\w)", "").length()) / 2);
                if(strCurrentLine.trim().startsWith("if")){
                    //if(total > 0)  // 'if' detected
                    {
                        //Detecting &&
                        //total = total + ((strCurrentLine.length() - strCurrentLine.replaceAll("&&", "").length()) / 2);
                        //Detecting &
                        //total = total + ((strCurrentLine.length() - strCurrentLine.replaceAll("(?<!&)&(?![&=])", "").length()));
                        //Detecting ||
                        //total = total + ((strCurrentLine.length() - strCurrentLine.replaceAll("\\|\\|", "").length()) / 2);
                        //Detecting |
                        //total = total + ((strCurrentLine.length() - strCurrentLine.replaceAll("(?<!\\|)\\|(?!\\|)", "").length()));
                        
                        //System.out.println(total);
                    }
                }
                else
                {
                    //System.out.println("No");
                }
                
                for(int i=0;i<Mtable.getRowCount();i++){
                    
                    int summethodCount = 0;
                    int sumWmrt = 0;
                    int sumNpdtp = 0;
                    int sumNcdtp = 0;
                    int sumWpdtp = 0;
                    int sumWcdtp = 0;
                    int sumCm = 0;
                    
                if (strCurrentLine.trim().length() != 0) {
                    System.out.println(strCurrentLine);
                    strCurrentLine = strCurrentLine.trim();

                }
                if (strCurrentLine.contains("//")) {
                    System.out.println(strCurrentLine.substring(0, strCurrentLine.indexOf("//")));
                    strCurrentLine = strCurrentLine.substring(0, strCurrentLine.indexOf("//"));
                    
                }  
            }
                
                Wpdtp = Integer.parseInt(primitiveparameter.getText());
                Wcdtp = Integer.parseInt(compositeparameter.getText());
                
                Cm = (Integer) new method_1().methodCount(strCurrentLine).get(0) + (Integer.parseInt(primitiveparameter.getText()) * (Integer) new method_1().methodCount(strCurrentLine).get(1)) + (Integer.parseInt(compositeparameter.getText()) * (Integer) new method_1().methodCount(strCurrentLine).get(2));
                Object[] row = {LineNo++, strCurrentLine, new method_1().methodCount(strCurrentLine).get(0), new method_1().methodCount(strCurrentLine).get(1), new method_1().methodCount(strCurrentLine).get(2), Cm};            
                model.addRow(row);
            }
        } catch (IOException ex) {
            Logger.getLogger(Weight3.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
     public void setWeightData(File ff) throws IOException {
        Weight3 ne =new  Weight3();
        DefaultTableModel model = (DefaultTableModel) Mtable.getModel();
        int Wmrt = 0;
        int Npdtp =0;
        int Ncdtp = 0;
        int Wpdtp = 0;
        int Wcdtp =0;
        int Cm = 0;
        int count = 0;
        
        FileReader fr = new FileReader(ff);
        BufferedReader br = new BufferedReader(fr);
              
        String strCurrentLine = null;
        strCurrentLine = br.readLine();
       
        while ((strCurrentLine = br.readLine()) != null) {
            {
               
            if(strCurrentLine.trim().startsWith("for")||strCurrentLine.trim().startsWith("while")||strCurrentLine.trim().startsWith("do-while"))
            {
                //Wtcs=Integer.parseInt(FWD.getText());                
            }
            else if(strCurrentLine.trim().startsWith("if")||strCurrentLine.trim().startsWith("else if")||strCurrentLine.trim().startsWith("switch"))
            {
                ///Wtcs=Integer.parseInt(EIF.getText()); 
            }            
            else if(strCurrentLine.trim().startsWith("case"))
            {
               // Wtcs=Integer.parseInt(CaseV.getText()); 
            }
            else{
                
                Cm=0;
                                
                }
        }
            //formula
            //Cv = Wvs * ((Wpdtv * Npdtv) + (Wcdtv * Ncdtv));
    
            //Object[] row = {LineNo++, strCurrentLine, new size_1().keywordCount(strCurrentLine), new size_1().identifierCount(strCurrentLine), new size_1().operatorCount(strCurrentLine), new size_1().numericalValueCount(strCurrentLine), new size_1().stringLiteralsCount(strCurrentLine)};            
            //model.addRow(row);      
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser jf = new JFileChooser();
        int aa = jf.showOpenDialog(null);

        if(aa == JFileChooser.APPROVE_OPTION){
            char cbuf[] = null;
            ff = jf.getSelectedFile();
            fileUpload.setText(ff.getName());

            try {
                fr = new FileReader(ff);
                TextArea1.read(fr, "");
                code = TextArea1.getText();
            } catch (Exception ex) {
                Logger.getLogger(interface01.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                try {
                    fr.close();
                } catch (IOException ex) {
                    Logger.getLogger(interface01.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       setVisible(false);
       new interface01().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void methodcompositeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_methodcompositeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_methodcompositeActionPerformed

    private void methodprimitiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_methodprimitiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_methodprimitiveActionPerformed

    private void compositeparameterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compositeparameterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compositeparameterActionPerformed

    private void methodreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_methodreturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_methodreturnActionPerformed

    private void primitiveparameterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primitiveparameterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_primitiveparameterActionPerformed

    private void fileUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileUploadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileUploadActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Wmrt = Integer.parseInt(.getText());
        int Wpdtp=0;
        int Wcdtp=0;
        Wpdtp = Integer.parseInt(primitiveparameter.getText());
        Wcdtp = Integer.parseInt(compositeparameter.getText());
        
  
            DefaultCategoryDataset dataset = new DefaultCategoryDataset( );
        

            //dataset.setValue(Wkw, "Weight", "Wkw");
            dataset.setValue(Wpdtp, "Weight", "Wpdtp");
            dataset.setValue(Wcdtp, "Weight", "Wcdtp");
            
            JFreeChart chart = ChartFactory.createBarChart3D("Methods", "Factors", "Weightage", dataset, PlotOrientation.VERTICAL, false, true, false);
            CategoryPlot p = chart.getCategoryPlot();
            ChartFrame frame = new ChartFrame("Bar Chart for Methods", chart);
            frame.setVisible(true);
            frame.setSize(600,550);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       fileUpload.setText("");
       TextArea1.setText("");
       methodprimitive.setText("");
       methodcomposite.setText("");
       methodreturn.setText("");
       primitiveparameter.setText("");
       compositeparameter.setText("");
       
       Mtable.setModel(new DefaultTableModel(null, new String[]{"Line no", "Program statements", "Wmrt", "Npdtp", "Ncdtp", "Cm"}));
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Size.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Size.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Size.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Size.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Weight3().setVisible(true);
            }
        });
    }
        
        
        
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Mtable;
    private javax.swing.JTextArea TextArea1;
    private javax.swing.JTextField compositeparameter;
    private javax.swing.JTextField fileUpload;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField methodcomposite;
    private javax.swing.JTextField methodprimitive;
    private javax.swing.JTextField methodreturn;
    private javax.swing.JTextField primitiveparameter;
    // End of variables declaration//GEN-END:variables
}      
